# Generated by Django 4.1.2 on 2022-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Aboutus',
            fields=[
                ('title', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.FileField(blank=True, null=True, upload_to='imgAboutUs', verbose_name='Картинка')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'db_table': 'API_AboutUs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Analyses',
            fields=[
                ('short_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Короткий заголовок')),
                ('long_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длинный заголовк')),
                ('is_unique', models.BooleanField(blank=True, verbose_name='Уникальный')),
                ('research_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Код анализа')),
                ('research_time', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Время анализа')),
                ('biomaterial', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Биоматериал')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('preparation_doctor', models.TextField(blank=True, null=True, verbose_name='Инструкция для врача ')),
                ('banner_img', models.FileField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Картинка для баннера')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип анализа')),
                ('document_img', models.FileField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Картинка для документа')),
                ('main_img', models.FileField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Главная картинка')),
                ('description_patient', models.TextField(blank=True, null=True, verbose_name='Описание для пациентов')),
                ('preparation_patient', models.TextField(blank=True, null=True, verbose_name='Инструкция для пациентов')),
                ('description_doctor', models.TextField(blank=True, null=True, verbose_name='Описание для врачей')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'db_table': 'API_Analyses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Appointments',
            fields=[
                ('title_appointment', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Заголовок записи')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'API_Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Contacts',
            fields=[
                ('address', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('map', models.CharField(blank=True, max_length=250, null=True, verbose_name='Карта')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'API_Contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_news', models.FileField(blank=True, max_length=255, null=True, upload_to='imgNews')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'API_News',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_notification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок уведомления')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'API_Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок акций')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'API_Promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Qaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'db_table': 'API_QaAs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок результатов')),
                ('isready', models.IntegerField(blank=True, db_column='isReady', null=True, verbose_name='Готовность')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='fileResult')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'API_Results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=15, null=True, verbose_name='Фамилия')),
                ('avatar', models.FileField(blank=True, max_length=255, null=True, upload_to='imgAvatar')),
                ('text_review', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'API_Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('password2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('avatar', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Имя пользователя')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'API_Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequelizemeta',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SequelizeMeta',
                'managed': False,
            },
        ),
    ]
